[package]
name = "uttt-server"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2021"

[dependencies]
common = { package = "uttt-common", path = "../common" }

rand = "0.8.5"
serde = "1.0.193"

[features]
auto_connect = []
