[package]
name = "uttt-common"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
ron = "0.8"

rand = "0.8.5"
